### ISSUE TITLE
Separate Flow Blob handling from client/invoke API 

### ISSUE THREAD

**Issue by zootalures** [fnproject/flow#84]
The flow service already de-couples node state from nodes internally using the blobstore abstraction.  

We would like to separate the semantics of a flow from handling of any data from that flow - that would allow: 

* Separating scaling concerns (data ingress/egress and associated storage to flow service and same for blobs) 
* Customer data isolation (no customer data except flow metadata  in Flow domain) 

Wherever we send blob data to the flow service now, we should send a client-side ref to the same data. 

The data itself can be stored by the client or via a  client-side service (TBD) 
 
Corollaries: 

* This simplifies both the client and invokes APIs - and would allow us to ditch multipart in favour of JSON or PB
* Http/Fn  Invoke will need to be handled specially as the invoke client needs to read/write data from the blob store 

Issues: 
* need to understand how we are going to expire/delete blob data independently of the flow service. 
* Need to find an apt blob store (e.g. object-store/ KV store traditional DB etc) 
* Will increase complexity on FDK side - need to moderate this. 
* Ownership of blobs - blobs should be tied to specific flows (and possibly stages) 
 

Plan: 
 - [x] Remove blobs as streams from flow-api
 - [x] Build blob store endpoint in flow-svc with its own API  (we can split out later) .
 - [x] Make blobstore streaming (deals in io.Reader rather than bytes 
 -  Initial Backends (based on persistence.BlobStore API now) 
     - [x] inmem 
     - [x] existing Sql backend   
     - [ ] S3 API
-  [x] Refactor Java FDK to support blob service

**Comment by treeder** [comment]
This could (should?) share the same store that will be used for logs: https://github.com/fnproject/fn/issues/473 , so operators don't have to maintain two of them. Both have similar issues to solve as well, such as expiration.

**Comment by zootalures** [comment]
Yep definitely, it will be back-end agnostic in some form as well. 

I think storage needs to be behind a facade service (i.e.  FDK -> BlobSvc -> Store) rather than going direct from FDK -> Store  as it lets you do access control per flow (and saves effort in FDKs).

**Comment by msgodf** [comment]
Current things to complete:

* [ ] Java Graph API changes
* [X] Blob API
* [ ] Invoke API messages
* [ ] Java Invoke API 
* [ ] Stage validation (check for blobs)

**Comment by zootalures** [comment]
Done, except S3 API backend, leaving for now.
